Initial sync can use model methods
vfonic/webflow_sync pull request #56
Opened 2024-05-30 13:21 UTC by aedificator-nl

The initial sync job now uses `should_skip_webflow_sync?` and `webflow_collection_id` methods from the model.

This way any adjustments to those methods (for example hardcoding a `webflow_collection_id` instead of using the `slug`) are used in the `initial_sync_job` as well.

Also includes a Rails upgrade. This does not seem to break anything, but was needed to get it working locally because of a lagging `nio4r` version.

2024-05-30 18:08 UTC, vfonic approved these changes
Impeccable! Thank you!

Let me see how I can have GitHub run the build and I'll release this as patch x.x.X version update. I think this could be considered as a bug fix rather than a feature addition.

Let me know if you believe differently.
I'll also try to upgrade to the newly released gem version from one of my Rails apps which are not on Rails 7.1.x to see if Bundler will try to update and fail or will it stay on the older version until I upgrade to Rails 7.1.x.

2024-05-30 18:08 UTC, vfonic commented on spec/models/concerns/webflow_sync/callbacks_spec.rb
> +        expect(article.should_skip_webflow_sync?).to be false
Thanks! 👍

2024-05-30 18:25 UTC, vfonic commented
Can you please have a look and fix the build issue(s)?

2024-06-03 17:07 UTC, vfonic requested changes
Looks like your RubyMine IDE files got checked in as well. Can you please remove them from the PR?

I have this in my `~/.gitignore_global`:

```
*~
.DS_Store
.idea/*
.pry_history
.vscode/*

.yarn/*
!.yarn/patches
!.yarn/releases
!.yarn/plugins
!.yarn/sdks
!.yarn/versions
.pnp.*

/TAGS

*.code-workspace
TODO
```

I hope it helps.

2024-06-04 07:04 UTC, aedificator-nl commented
I have fixed some issues. The current issues with the test seem to have to do with the env vars, in test I think `WEBFLOW_SITE_ID` is set to `<WEBFLOW_SITE_ID>`, which errors out the tests. Could you replace this with an allowed dummy id?

2024-06-05 22:20 UTC, merged

2024-06-05 22:32 UTC, vfonic commented
I don't know how to allow PRs from forks to share Github Actions secrets. I tested your changes both locally and I pushed it to a branch on this repo and the build passed.

I released this as v9.0.0 due to many gems being updated due to security issues.
I don't mind bumping major version number (as you can tell) than breaking someone's app because it feel like the changes don't justify a major version bump.

2024-06-06 07:36 UTC, aedificator-nl commented
Thanks! Great that it all worked out!

2025-04-25 22:56 UTC, sins921 approved these changes

2025-04-25 23:03 UTC, vfonic commented
WTF just happened here? :) How was this PR merged automatically?

2025-04-25 23:07 UTC, vfonic commented
@aedificator-nl seems like the branch in your fork was deleted? https://github.com/aedificator-nl/webflow_sync/branches

https://github.com/aedificator-nl/webflow_sync/tree/feature/initial-sync-should-use-model-settings

That caused the false alarm that this was already merged, while it wasn't.

2025-04-29 11:56 UTC, aedificator-nl commented
I have restored the branch. As far as I can see you have merged the changes into your master branch on the 6th of June 2024, after which I deleted the branch.